class Cars{

  String carName;
  String carImage;
  String description;
  String founder;
  Cars({this.carName, this.carImage, this.description, this.founder});
}

List<Cars> carList = [

  Cars(carImage: "assets/images/1.jpg", description: "McLaren Automotive replaced McLaren Cars in 2010. McLaren Cars was founded in 1985.[4] The company went on to release the McLaren F1 in 1992. Between 1994 and 2010, McLaren Cars was registered as a 'dormant company', before the founding of McLaren Automotive in 2010. The new company was originally separate from the existing McLaren companies to enable investment in the new venture, but was brought together in July 2017 after Dennis sold his shares in McLaren Automotive and McLaren Technology Group.McLaren's Formula One founder Bruce McLaren was born in 1937.[5] McLaren learned about cars and engineering at his parent's service station and workshop in his hometown, Auckland, New Zealand. By 15, he had entered a local hillclimb in an Austin 7 Ulster; winning his first race in the car.[6] In 1958, McLaren arrived in the United Kingdom with the ‘Driver to Europe’ scheme, intended to help Australian and New Zealand racers to compete in Europe. His mentor, Jack Brabham introduced him to Cooper Cars, a small team based in Surbiton, Surrey. Auspiciously starting his Formula One career in 1958, McLaren joined the Formula One team a year later. That same year, he won the US Grand Prix at age 22, making him the youngest Grand Prix winner to that date.[7] He stayed with Cooper for a further seven years, winning three more Grands Prix and other races, driving for Jaguar and Aston Martin, & winning the 24 Hours of Le Mans in 1966 with Ford.McLaren founded Bruce McLaren Motor Racing in 1963. A year later, the company built the first McLaren race car – the M1A; 24 were produced. Its successor, the M1B, allowed McLaren into the Can-Am championship and emerged the dominant victor with 43 victories, almost three times more than rival Porsche.[8] In 1965, the first McLaren Formula One car, the M2B, debuted at the Monaco Grand Prix.After his victories and time in the F3, McLaren was designing and testing a prototype M6GT-registered OBH 500H, a light sports car with an estimated top speed of 165 mph and zero to 100 mph time of eight seconds.[9] However, McLaren died in a car accident in 1970 before the prototype could be completed.", founder: "Ron Dennis", carName: "McLaren"),
   Cars(carImage: "assets/images/2.jpg", description: "McLaren Automotive replaced McLaren Cars in 2010. McLaren Cars was founded in 1985.[4] The company went on to release the McLaren F1 in 1992. Between 1994 and 2010, McLaren Cars was registered as a 'dormant company', before the founding of McLaren Automotive in 2010. The new company was originally separate from the existing McLaren companies to enable investment in the new venture, but was brought together in July 2017 after Dennis sold his shares in McLaren Automotive and McLaren Technology Group.McLaren's Formula One founder Bruce McLaren was born in 1937.[5] McLaren learned about cars and engineering at his parent's service station and workshop in his hometown, Auckland, New Zealand. By 15, he had entered a local hillclimb in an Austin 7 Ulster; winning his first race in the car.[6] In 1958, McLaren arrived in the United Kingdom with the ‘Driver to Europe’ scheme, intended to help Australian and New Zealand racers to compete in Europe. His mentor, Jack Brabham introduced him to Cooper Cars, a small team based in Surbiton, Surrey. Auspiciously starting his Formula One career in 1958, McLaren joined the Formula One team a year later. That same year, he won the US Grand Prix at age 22, making him the youngest Grand Prix winner to that date.[7] He stayed with Cooper for a further seven years, winning three more Grands Prix and other races, driving for Jaguar and Aston Martin, & winning the 24 Hours of Le Mans in 1966 with Ford.McLaren founded Bruce McLaren Motor Racing in 1963. A year later, the company built the first McLaren race car – the M1A; 24 were produced. Its successor, the M1B, allowed McLaren into the Can-Am championship and emerged the dominant victor with 43 victories, almost three times more than rival Porsche.[8] In 1965, the first McLaren Formula One car, the M2B, debuted at the Monaco Grand Prix.After his victories and time in the F3, McLaren was designing and testing a prototype M6GT-registered OBH 500H, a light sports car with an estimated top speed of 165 mph and zero to 100 mph time of eight seconds.[9] However, McLaren died in a car accident in 1970 before the prototype could be completed.",  founder: "Ron Dennis", carName: "McLaren"),
    Cars(carImage: "assets/images/3.jpg", description: "Automobiles Ettore Bugatti was a French car manufacturer of high-performance automobiles, founded in 1909 in the then-German city of Molsheim, Alsace by the Italian-born industrial designer Ettore Bugatti. The cars were known for their design beauty and for their many race victories", founder: "Ettore Bugatti", carName: "Bugatti"),
     Cars(carImage: "assets/images/4.jpg", description: "Automobiles Ettore Bugatti was a French car manufacturer of high-performance automobiles, founded in 1909 in the then-German city of Molsheim, Alsace by the Italian-born industrial designer Ettore Bugatti. The cars were known for their design beauty and for their many race victories", founder: "Ettore Bugatti", carName: "Bugatti"),
      Cars(carImage: "assets/images/5.jpg", description: "Automobili Lamborghini S.p.A. is an Italian brand and manufacturer of luxury sports cars and SUVs based in Sant'Agata Bolognese. The company is owned by the Volkswagen Group through its subsidiary Audi.",  founder: " Ferruccio Lamborghini", carName: "Lamborghini"),
       Cars(carImage: "assets/images/6.jpg", description: "McLaren Automotive replaced McLaren Cars in 2010. McLaren Cars was founded in 1985.[4] The company went on to release the McLaren F1 in 1992. Between 1994 and 2010, McLaren Cars was registered as a 'dormant company', before the founding of McLaren Automotive in 2010. The new company was originally separate from the existing McLaren companies to enable investment in the new venture, but was brought together in July 2017 after Dennis sold his shares in McLaren Automotive and McLaren Technology Group.McLaren's Formula One founder Bruce McLaren was born in 1937.[5] McLaren learned about cars and engineering at his parent's service station and workshop in his hometown, Auckland, New Zealand. By 15, he had entered a local hillclimb in an Austin 7 Ulster; winning his first race in the car.[6] In 1958, McLaren arrived in the United Kingdom with the ‘Driver to Europe’ scheme, intended to help Australian and New Zealand racers to compete in Europe. His mentor, Jack Brabham introduced him to Cooper Cars, a small team based in Surbiton, Surrey. Auspiciously starting his Formula One career in 1958, McLaren joined the Formula One team a year later. That same year, he won the US Grand Prix at age 22, making him the youngest Grand Prix winner to that date.[7] He stayed with Cooper for a further seven years, winning three more Grands Prix and other races, driving for Jaguar and Aston Martin, & winning the 24 Hours of Le Mans in 1966 with Ford.McLaren founded Bruce McLaren Motor Racing in 1963. A year later, the company built the first McLaren race car – the M1A; 24 were produced. Its successor, the M1B, allowed McLaren into the Can-Am championship and emerged the dominant victor with 43 victories, almost three times more than rival Porsche.[8] In 1965, the first McLaren Formula One car, the M2B, debuted at the Monaco Grand Prix.After his victories and time in the F3, McLaren was designing and testing a prototype M6GT-registered OBH 500H, a light sports car with an estimated top speed of 165 mph and zero to 100 mph time of eight seconds.[9] However, McLaren died in a car accident in 1970 before the prototype could be completed.",  founder: "Ron Dennis", carName: "McLaren"),
        
];